### ISSUE TITLE
how about proguard

### ISSUE THREAD

**Issue by drogbababa** [andremion/Louvre#10]
how to write proguard rules?
if dont wirite anythiing,when generated signed apk it will failed.jump out some warinings such as
Warning:com.squareup.picasso.OkHttpDownloader: can't find referenced class com.squareup.okhttp.OkHttpClient

**Comment by andremion** [comment]
I didn't have any proguard issue in signed apks.
But you can use ````-dontwarn com.squareup.picasso.**```` in your ````proguard-rules.pro```` file
