### ISSUE TITLE
Keep selection

### ISSUE THREAD

**Issue by dariob** [andremion/Louvre#11]
Great library, thank you for sharing.
Would be great to choose if Louvre must keep last selection or not. This way users are able to know if an images was already selected or not.
Some ideas to implement it?

**Comment by andremion** [comment]
Hi @dariob, 
It's a good change request.
Maybe this can be setup as ````louvre.setCurrentSelection(selection)```` with ````selection```` being a ````List<Uri>````
What do you think about it?

**Comment by dariob** [comment]
Hi @andremion, yep will be great and a powerful  UX improvement.
