### ISSUE TITLE
The crash connected with PhotoView library

### ISSUE THREAD

**Issue by cryser29** [andremion/Louvre#16]
Thank you for the great library!

## Context

I don't use PhotoView separately but received following crash report:

```
Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2372)
       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2064)
```

I found following resolved issues of PhotoView library that are connected with the crash above [#31](https://github.com/chrisbanes/PhotoView/issues/31) and [#293](https://github.com/chrisbanes/PhotoView/issues/293). The author of PhotoView described the [solution of this problem](https://github.com/chrisbanes/PhotoView#issues-with-viewgroups).

## Possible Fix

Replace `android.support.v4.view.ViewPager` in `activity_preview.xml` with [HackyViewPager](https://github.com/chrisbanes/PhotoView/blob/master/sample/src/main/java/com/github/chrisbanes/photoview/sample/HackyViewPager.java).

Thank you!

**Comment by andremion** [comment]
Thank you @cryser29 for your tip! 👏🏻
If you prefer, you can open a PR with the solution so I can review it and later merge it. 😎
### Suggestion
Put the `HackyViewPager` code into `com.andremion.louvre.util` package 😉

Thanks!
