### ISSUE TITLE
The done FAB disappears

### ISSUE THREAD

**Issue by JailbirdInteractive** [andremion/Louvre#4]
The done FAB disappears.

## Context

The user is choosing an image and taps the image to see it larger. Once they go back to the grid view the fab is gone, making it impossible to finish the selection.

This is occurring in *Android Nougat devices*.

## Process

1. User taps on some image to view in fullscreen mode
2. User taps on back button

## Expected result

The done FAB is shown

## Current result

The done FAB is not shown

**Comment by andremion** [comment]
Please, could you format the issue with [ISSUE_TEMPLATE.md](https://github.com/andremion/Louvre/blob/master/ISSUE_TEMPLATE.md) ?

And to mention what the Android version this is reproducible.

Thank you.

**Comment by gab07** [comment]
Hey, I have the same issue on Android 7.1.2 (only device tested) this was fixed ?

**Comment by andremion** [comment]
Yes @gab07 , this was fixed. That's the reason I closed this issue.
Try the latest version of library.
Thanks.

**Comment by gab07** [comment]
Well I'm using version 1.0.1 (the version of the readme) and I'm having this issue. Is there a newer version?
