### ISSUE TITLE
Unable to get images after selection

### ISSUE THREAD

**Issue by Anu07** [andremion/Louvre#5]
I am getting this message:
Invalid image.
java.io.IOException: Invalid marker: 89

**Comment by andremion** [comment]
Hi @Anu07 

Could you give me more context about this error? How can I reproduce it?

Thank you.

**Comment by Anu07** [comment]
After selecting images from gallery,I keep on receiving this error and end up with nothing.
Invalid image.
java.io.IOException: Invalid marker: 89
Exiftags kinda error it shows.

Thanks

**Comment by andremion** [comment]
The Louvre just do this after clicking on confirm selection:
````
Intent data = new Intent();
data.putExtra(EXTRA_SELECTION, (ArrayList<Uri>) mFragment.getSelection());
setResult(RESULT_OK, data);
finish();
````
So, could be some code called after this from your app side, don't it?

**Comment by andremion** [comment]
@Anu07 , Can I close this issue?
