### ISSUE TITLE
The app is crashing with a runtime exception

### ISSUE THREAD

**Issue by madhavbansal23** [andremion/Louvre#9]
Te gallery activity is not starting and is throwing this error. Im not able to figure it out. This is not due to proguard as I'm on the debug mode. The parceable I guess is not working properly
Here is the stacktrace

`Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{com.madcode.dslrphoto/com.andremion.louvre.home.GalleryActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@60fcb0b: Unmarshalling unknown type code 7209057 at offset 1228
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3320)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3416)
android.app.ActivityThread.access$1100 (ActivityThread.java:230)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1822)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7409)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
arrow_drop_down
Caused by java.lang.RuntimeException: Parcel android.os.Parcel@60fcb0b: Unmarshalling unknown type code 7209057 at offset 1228
android.os.Parcel.readValue (Parcel.java:2341)
android.os.Parcel.readArrayMapInternal (Parcel.java:2620)
android.os.BaseBundle.unparcel (BaseBundle.java:221)
android.os.Bundle.getSparseParcelableArray (Bundle.java:856)
com.android.internal.policy.PhoneWindow.restoreHierarchyState (PhoneWindow.java:2334)
android.app.Activity.onRestoreInstanceState (Activity.java:1177)
android.app.Activity.performRestoreInstanceState (Activity.java:1122)
android.app.Instrumentation.callActivityOnRestoreInstanceState (Instrumentation.java:1192)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3287)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3416)
android.app.ActivityThread.access$1100 (ActivityThread.java:230)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1822)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7409)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)`

**Comment by andremion** [comment]
Hi @madhavbansal23 ,
I need more information about that.
- What is the Android version?
- The issue occurs in any device?
- Can you show me the code used to open the Louvre?
- The Louvre demo from Play store works without any issues?

**Comment by madhavbansal23** [comment]
Hi @andremion 
The App is working fine on some devices and is crashing on some. All crashes are on lollipop and marshmallow devices. (Api 22 and 23)
Majorly crashing on Samsung, motorola and vivo devices.

The code used to open Louvre is 
`Louvre.init(Menuclass.this)
                        .setRequestCode(REQUEST_MULTIPLE)
                        .setMaxSelection(16)
                        .setMediaTypeFilter(Louvre.IMAGE_TYPE_JPEG, Louvre.IMAGE_TYPE_PNG)
                        .open();`

OnActivityResultCode is 
`List<Uri> imgUri = GalleryActivity.getSelection(data);`

**Comment by andremion** [comment]
I'm gonna mark that as unreproducible.
Let me know if that still happens.
